### ISSUE TITLE
add more resources to prod vm

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-dbaas#131]
```

            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "6Gi"
                cpu: "2"
```
