### ISSUE TITLE
add resources to vmauth in prod

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-dbaas#133]
```

            resources:
              requests:
                memory: "500Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1"
```
